image: node:latest

stages:
  - test
  - deploy



test:
  stage: test

  services:
    - mongo:latest

  variables:
    MONGO_URI: 'mongodb://mongo/test'
    NODE_ENV: 'test'

  script:
    - npm install
    - npm test