image: node:latest

stages:
  - test
  - deploy

test:
  stage: test
  variables:
    MONGO_URI: 'mongodb://localhost/test'
    NODE_ENV: 'test'
  services:
    - mongo:latest
  script:
    - npm install
    - npm test