image: node:latest

stages:
  - test
  - deploy

services:
    - mongo:latest

variables:
  MONGO_URI: 'mongodb://mongo/test'
  NODE_ENV: 'test'

test:
  stage: test

  script:
    - npm install
    - npm test